### ISSUE TITLE
Not importing anything.

### ISSUE THREAD

**Issue by EA3HZZ** [firegento/FireGento_FastSimpleImport2_Demo#1]
Steps I followed:
1. Just installed the demo, and FireGento_FastSimpleImport2 from the repos,
2. run bin/magento setup:upgrade, 
3. run bin/magento setup:di:compile, 
4. and call for example:  bin/magento fastsimpleimport2demo:products:importconfigurable and throws this output:

```
Import started
1: Begin data validation
2: This file does not contain any data.
Import finished. Elapsed time: 0.74s
```

> php -v =PHP 5.5.35 (cli)
> Magento = 2.0.4

**Comment by EA3HZZ** [comment]
If I comment the lines 66 and 69 in FastSimpleImport2/Model/Importer, I can view other error:

`Error in data structure: entity values are mixed`

But no luck with the solutions around the www....

I think it could be problem in magento 2 itself... manual importing a csv is not working too...

**Comment by EliasKotlyar** [comment]
Hello ohtaron,

I also think its a issue with your magento2 installation because the usual csv-import/export should work out of the box. Consider installing a fresh magento2 using this tutorial : http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html

Greetings
Elias

**Comment by EA3HZZ** [comment]
Finally solved reinstalling  magento from composer.
Thx EliasKotlyar!
