### ISSUE TITLE
Not working with Magento 2.3

### ISSUE THREAD

**Issue by ankit-sf** [firegento/FireGento_FastSimpleImport2_Demo#11]
Not working with Magento 2.3

here is sample response after running command
php bin/magento fastsimpleimportdemo:products:importsimple

1: Begin data validation
2: This file does not contain any data.
Import finished. Elapsed time: 2.94s

**Comment by ankit-sf** [comment]
issue is magento issue

**Comment by AurelienLavorel** [comment]
@ankit-sf do you have the Magento issue link please?
