### ISSUE TITLE
Multiselect attribute example

### ISSUE THREAD

**Issue by remklov** [firegento/FireGento_FastSimpleImport2_Demo#2]
I try to import a multiselect attribute, but i cannot get it working.
I tried to pass:
- array of value ids
- array of values
- commaseparated ids
- commaseparated values

``` PHP
$data[] = [
    ...
    'attributeCode' => ["355", "356"],
    'attributeCode' => "355,356",
    'attributeCode' => [355, 356],
    'attributeCode' => ["Val1", "Val2"],
    'attributeCode' => "Val1,Val2",
    ...
];
```

Can you add an example for an multiselect attribute to the module, or copy some snippet here?

Thanks in advance!

**Comment by EliasKotlyar** [comment]
Hello Benevolk,

You just need to use "|" as separator. I also have provided an example for this type of import. 

Greetings
Elias
